#!/bin/sh
modprobe libcomposite
cd /sys/kernel/config/usb_gadget/

mkdir -p g1
cd g1

echo 0x1d6b > idVendor
echo 0x0104 > idProduct
echo 0x0100 > bcdDevice
echo 0x0200 > bcdUSB

mkdir strings/0x409
echo "12345678"    > strings/0x409/serialnumber
echo "KeyboardTestCCN." > strings/0x409/manufacturer
echo "Generic USB Keyboard"  > strings/0x409/product

mkdir -p functions/hid.usb0
echo 1 > functions/hid.usb0/protocol
echo 0 > functions/hid.usb0/subclass
echo 8 > functions/hid.usb0/report_length
#echo -ne \\x05\\x01\\x09\\x06\\xa1\\x01\\x05\\x07\\x19\\xe0\\x29\\xe7\\x15\\x00\\x25\\x01\\x75\\x01\\x95\\x08\\x81\\x02\\x95\\x01\\x75\\x08\\x81\\x03\\x95\\x05\\x75\\x01\\x05\\x08\\x19\\x01\\x29\\x05\\x91\\x02\\x95\\x01\\x75\\x03\\x91\\x03\\x95\\x06\\x75\\x08\\x15\\x00\\x25\\x65\\x05\\x07\\x19\\x00\\x29\\x65\\x81\\x00\\xc0 > functions/hid.usb0/report_desc

#echo -ne \\x06\\x00\\xFF\\xA1\\x01\\x15\\x00\\x26\\xFF\\x00\\x75\\x04\\x85\\x01\\x95\\x6F\\x09\\x01\\x81\\x02\\x85\\x02\\x09\\x01\\x91\\x02\\xC0 > functions/hid.usb0/report_desc
echo -ne \\x06\\x00\\xFF\\xA1\\x01\\x15\\x00\\x26\\xFF\\x00\\x75\\x20\\x85\\x01\\x95\\x6F\\x09\\x01\\x81\\x02\\x85\\x02\\x09\\x01\\x91\\x02\\xC0 > functions/hid.usb0/report_desc

mkdir -p configs/c.1
echo 250 > configs/c.1/MaxPower

mkdir -p configs/c.1/strings/0x409
echo "Config 1" > configs/c.1/strings/0x409/configuration
ln -s functions/hid.usb0 configs/c.1

ls /sys/class/udc > UDC
chmod 777 /dev/hidg0
